laravel/app/Http/routes.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('produtos/novo', ['as' => 'produtos.novo', 'uses' => 'ProdutosController@novo']);
Route::get('produtos/{produtos_categoria_slug?}', ['as' => 'produtos.index', 'uses' => 'ProdutosController@index']);
Route::get('produtos/{produtos_categoria_slug}/{produto_slug}', ['as' => 'produtos.show', 'uses' => 'ProdutosController@show']);
Route::get('servicos', ['as' => 'servicos', 'uses' => 'ServicosController@index']);
Route::get('downloads/{downloads_categoria_slug?}', ['as' => 'downloads', 'uses' => 'DownloadsController@index']);
Route::get('busca', ['as' => 'busca', 'uses' => 'HomeController@busca']);
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);
Route::post('newsletter', ['as' => 'newsletter', 'uses' => 'HomeController@newsletter']);


// Painel
Route::group(['prefix' => 'painel', 'namespace' => 'Painel', 'middleware' => 'auth'], function() {
    Route::get('/', ['as' => 'painel', 'uses' => 'HomeController@index']);
    Route::resource('banners', 'BannersController');
    Route::get('produtos/select/{categorias}', 'ProdutosController@produtos');
    Route::resource('produtos/destaques', 'ProdutosDestaquesController');
    Route::resource('produtos/categorias', 'ProdutosCategoriasController');
    Route::resource('produtos', 'ProdutosController');
    Route::resource('produtos.imagens', 'ProdutosImagensController');
    Route::resource('servicos', 'ServicosController');
    Route::resource('downloads/categorias', 'DownloadsCategoriasController');
    Route::resource('downloads', 'DownloadsController');
    Route::resource('novo/imagens', 'NovoImagensController');
    Route::resource('novo', 'NovoController');
    Route::resource('contato/recebidos', 'ContatosRecebidosController');
    Route::resource('contato', 'ContatoController');
    Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
    Route::resource('newsletter', 'NewsletterController');
    Route::resource('usuarios', 'UsuariosController');
    Route::post('order', 'HomeController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


// Auth
Route::group(['prefix' => 'painel', 'namespace' => 'Auth'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

laravel/app/Models/Produto.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;
use Illuminate\Database\Eloquent\Model;

class Produto extends Model implements SluggableInterface
{
    use SluggableTrait;

    protected $sluggable = [
        'build_from' => 'titulo',
        'save_to'    => 'slug',
        'on_update'  => true
    ];

    protected $table = 'produtos';

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

    public function scopeSlug($query, $slug)
    {
        return $query->whereSlug($slug);
    }

    public function scopeCategoria($query, $categoria_id)
    {
        return $query->where('produtos_categoria_id', $categoria_id);
    }

    public function scopeDestaque($query)
    {
        return $query->where('destaque', 1);
    }

    public function categoria()
    {
        return $this->belongsTo('App\Models\ProdutoCategoria', 'produtos_categoria_id');
    }

    public function imagens()
    {
        return $this->hasMany('App\Models\ProdutoImagem', 'produto_id')->ordenados();
    }

    public function downloads()
    {
        return $this->hasMany('App\Models\Download', 'produto_id')->ordenados();
    }

    public function scopeBusca($query, $termo)
    {
        return $query->where('titulo', 'LIKE', "%$termo%")
                   ->orWhere('descricao', 'LIKE', "%$termo%");
    }
}

laravel/app/Http/Controllers/Painel/ProdutosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Http\Requests\ProdutosRequest;

use App\Models\ProdutoCategoria;
use App\Models\Produto;
use App\Helpers\CropImage;

class ProdutosController extends Controller
{
    private $categorias;

    private $image_config = [
        [
            'width'   => 275,
            'height'  => 200,
            'produto' => true,
            'path'    => 'assets/img/produtos/'
        ],
        [
            'width'   => 180,
            'height'  => 180,
            'produto' => true,
            'path'    => 'assets/img/produtos/thumbs/'
        ]
    ];

    public function __construct()
    {
        $this->categorias = ProdutoCategoria::ordenados()->lists('titulo', 'id');
    }

    public function index(Request $request)
    {
        $categorias = $this->categorias;
        $filtro     = $request->query('filtro');

        if (ProdutoCategoria::find($filtro)) {
            $produtos = Produto::ordenados()->categoria($filtro)->get();
        } else {
            $produtos = Produto::join('produtos_categorias as cat', 'cat.id', '=', 'produtos_categoria_id')
                ->orderBy('cat.ordem', 'ASC')
                ->orderBy('cat.id', 'DESC')
                ->select('produtos.*')
                ->ordenados()->get();
        }

        return view('painel.produtos.index', compact('categorias', 'produtos', 'filtro'));
    }

    public function create()
    {
        $categorias = $this->categorias;

        return view('painel.produtos.create', compact('categorias'));
    }

    public function store(ProdutosRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Produto::create($input);
            return redirect()->route('painel.produtos.index')->with('success', 'Produto adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar produto: '.$e->getMessage()]);

        }
    }

    public function edit(Produto $produto)
    {
        $categorias = $this->categorias;

        return view('painel.produtos.edit', compact('categorias', 'produto'));
    }

    public function update(ProdutosRequest $request, Produto $produto)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $produto->update($input);
            return redirect()->route('painel.produtos.index')->with('success', 'Produto alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar produto: '.$e->getMessage()]);

        }
    }

    public function destroy(Produto $produto)
    {
        try {

            $produto->delete();
            return redirect()->route('painel.produtos.index')->with('success', 'Produto excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir produto: '.$e->getMessage()]);

        }
    }

    public function produtos(ProdutoCategoria $categoria)
    {
        return $categoria->produtos()->where('destaque', 0)->orderBy('titulo', 'ASC')->lists('titulo', 'id')->toJson();
    }
}

laravel/app/Http/Controllers/ProdutosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ProdutoCategoria;
use App\Models\Produto;

use App\Models\Novo;
use App\Models\NovoImagem;

class ProdutosController extends Controller
{
    public function index(ProdutoCategoria $categoria)
    {
        if (! $categoria->exists) {
            $categoria = ProdutoCategoria::ordenados()->first() ?: \App::abort('404');
        }

        $produtos = $categoria->produtos()->paginate(9);

        return view('frontend.produtos.index', compact('categoria', 'produtos'));
    }

    public function show(ProdutoCategoria $categoria, Produto $produto)
    {
        return view('frontend.produtos.show', compact('categoria', 'produto'));
    }

    public function novo()
    {
        $novo    = Novo::first();
        $imagens = NovoImagem::ordenados()->get();

        return view('frontend.produtos.novo', compact('novo', 'imagens'));
    }
}

laravel/resources/views/painel/produtos/destaques/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Produtos /</small> Adicionar Destaque</h2>
    </legend>

    {!! Form::open(['route' => 'painel.produtos.destaques.store']) !!}

        @include('painel.produtos.destaques.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@stop

laravel/resources/views/painel/produtos/destaques/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('produtos_categoria_id', 'Categoria') !!}
    {!! Form::select('produtos_categoria_id', $categorias, '', ['class' => 'form-control select-categorias', 'placeholder' => 'Selecione']) !!}
</div>

<div class="form-group">
    {!! Form::label('produto_id', 'Produto') !!}
    {!! Form::select('produto_id', [], null, ['class' => 'form-control', 'placeholder' => 'Selecione uma Categoria']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.produtos.destaques.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/produtos/destaques/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.produtos.index') }}" class="btn btn-sm btn-default">
        &larr; Voltar para Produtos
    </a>

    <legend>
        <h2>
            <small>Produtos /</small> Destaques
            @if(count($destaques) < $limite)
            <a href="{{ route('painel.produtos.destaques.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Destaque</a>
            @endif
        </h2>
    </legend>

    @if(!count($destaques))
    <div class="alert alert-warning" role="alert">Nenhum destaque cadastrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Categoria</th>
                <th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($destaques as $destaque)
            <tr class="tr-row">
                <td>@if($destaque->categoria){{ $destaque->categoria->titulo }}@endif</td>
                <td>{{ $destaque->titulo }}</td>
                <td class="crud-actions">
                    {!! Form::open(array('route' => array('painel.produtos.destaques.destroy', $destaque->id), 'method' => 'delete')) !!}

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection