laravel/app/Http/routes.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('produtos/novo', ['as' => 'produtos.novo', 'uses' => 'ProdutosController@novo']);
Route::get('produtos/{produtos_categoria_slug?}', ['as' => 'produtos.index', 'uses' => 'ProdutosController@index']);
Route::get('produtos/{produtos_categoria_slug}/{produto_slug}', ['as' => 'produtos.show', 'uses' => 'ProdutosController@show']);
Route::get('servicos', ['as' => 'servicos', 'uses' => 'ServicosController@index']);
Route::get('downloads/{downloads_categoria_slug?}', ['as' => 'downloads', 'uses' => 'DownloadsController@index']);
Route::get('busca', ['as' => 'busca', 'uses' => 'HomeController@busca']);
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);
Route::post('newsletter', ['as' => 'newsletter', 'uses' => 'HomeController@newsletter']);


// Painel
Route::group(['prefix' => 'painel', 'namespace' => 'Painel', 'middleware' => 'auth'], function() {
    Route::get('/', ['as' => 'painel', 'uses' => 'HomeController@index']);
    Route::resource('banners', 'BannersController');
    Route::get('produtos/select/{categorias}', 'ProdutosController@produtos');
    Route::resource('produtos/destaques', 'ProdutosDestaquesController');
    Route::resource('produtos/categorias', 'ProdutosCategoriasController');
    Route::resource('produtos', 'ProdutosController');
    Route::resource('produtos.imagens', 'ProdutosImagensController');
    Route::resource('servicos', 'ServicosController');
    Route::resource('downloads/categorias', 'DownloadsCategoriasController');
    Route::resource('downloads', 'DownloadsController');
    Route::resource('novo/imagens', 'NovoImagensController');
    Route::resource('novo', 'NovoController');
    Route::resource('contato/recebidos', 'ContatosRecebidosController');
    Route::resource('contato', 'ContatoController');
    Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
    Route::resource('newsletter', 'NewsletterController');
    Route::resource('usuarios', 'UsuariosController');
    Route::post('order', 'HomeController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


// Auth
Route::group(['prefix' => 'painel', 'namespace' => 'Auth'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;
use App\Helpers\CropImage;

class BannersController extends Controller
{
    private $image_config = [
        'width'  => 1080,
        'height' => 430,
        'path'   => 'assets/img/banners/'
    ];

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Banner adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar banner: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $banner)
    {
        return view('painel.banners.edit', compact('banner'));
    }

    public function update(BannersRequest $request, Banner $banner)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $banner->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Banner alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar banner: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $banner)
    {
        try {

            $banner->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Banner excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir banner: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/DownloadsCategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DownloadsCategoriasRequest;
use App\Http\Controllers\Controller;

use App\Models\DownloadCategoria;

class DownloadsCategoriasController extends Controller
{
    public function index()
    {
        $categorias = DownloadCategoria::ordenados()->get();

        return view('painel.downloads.categorias.index', compact('categorias'));
    }

    public function create()
    {
        return view('painel.downloads.categorias.create');
    }

    public function store(DownloadsCategoriasRequest $request)
    {
        try {

            $input = $request->all();

            DownloadCategoria::create($input);
            return redirect()->route('painel.downloads.categorias.index')->with('success', 'Categoria adicionada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar categoria: '.$e->getMessage()]);

        }
    }

    public function edit(DownloadCategoria $categoria)
    {
        return view('painel.downloads.categorias.edit', compact('categoria'));
    }

    public function update(DownloadsCategoriasRequest $request, DownloadCategoria $categoria)
    {
        try {

            $input = $request->all();

            $categoria->update($input);
            return redirect()->route('painel.downloads.categorias.index')->with('success', 'Categoria alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar categoria: '.$e->getMessage()]);

        }
    }

    public function destroy(DownloadCategoria $categoria)
    {
        try {

            $categoria->delete();
            return redirect()->route('painel.downloads.categorias.index')->with('success', 'Categoria excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir categoria: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/DownloadsController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DownloadsRequest;
use App\Http\Controllers\Controller;

use App\Models\DownloadCategoria;
use App\Models\Download;
use App\Models\Produto;

class DownloadsController extends Controller
{
    private $categorias;
    private $produtos;

    public function __construct()
    {
        $this->categorias = DownloadCategoria::ordenados()->lists('titulo', 'id');
        $this->produtos   = Produto::orderBy('titulo', 'ASC')->lists('titulo', 'id');
    }

    public function index(Request $request)
    {
        $categorias = $this->categorias;
        $filtro     = $request->query('filtro');

        if (DownloadCategoria::find($filtro)) {
            $downloads = Download::ordenados()->categoria($filtro)->get();
        } else {
            $downloads = Download::join('downloads_categorias as cat', 'cat.id', '=', 'downloads_categoria_id')
                ->orderBy('cat.ordem', 'ASC')
                ->orderBy('cat.id', 'DESC')
                ->select('downloads.*')
                ->ordenados()->get();
        }

        return view('painel.downloads.index', compact('categorias', 'downloads', 'filtro'));
    }

    public function create()
    {
        $categorias = $this->categorias;
        $produtos   = $this->produtos;

        return view('painel.downloads.create', compact('categorias', 'produtos'));
    }

    public function store(DownloadsRequest $request)
    {
        try {

            $input = array_filter($request->all(), 'strlen');

            $input['arquivo'] = $this->uploadArquivo($input['arquivo']);

            Download::create($input);
            return redirect()->route('painel.downloads.index')->with('success', 'Download adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar download: '.$e->getMessage()]);

        }
    }

    public function edit(Download $download)
    {
        $categorias = $this->categorias;
        $produtos   = $this->produtos;

        return view('painel.downloads.edit', compact('categorias', 'produtos', 'download'));
    }

    public function update(DownloadsRequest $request, Download $download)
    {
        try {

            $input = array_filter($request->all(), 'strlen');

            if (isset($input['arquivo'])) {
                $input['arquivo'] = $this->uploadArquivo($input['arquivo']);
            }

            if (! isset($input['produto_id'])) {
                $input['produto_id'] = null;
            }

            $download->update($input);
            return redirect()->route('painel.downloads.index')->with('success', 'Download alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar download: '.$e->getMessage()]);

        }
    }

    public function destroy(Download $download)
    {
        try {

            $download->delete();
            return redirect()->route('painel.downloads.index')->with('success', 'Download excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir download: '.$e->getMessage()]);

        }
    }

    public function uploadArquivo($file)
    {
        $filePath = 'assets/downloads/';
        $fileName = preg_replace("([^\w\s\d\-_~,;:\[\]\(\).])", '', $file->getClientOriginalName());
        $fileName = date('YmdHis').'_'.$fileName;

        $file->move(public_path($filePath), $fileName);
        return $fileName;
    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;

class HomeController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i));
        }

        return json_encode($data);
    }

}

laravel/app/Http/Controllers/Painel/NewsletterController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Newsletter;

class NewsletterController extends Controller
{
    public function index()
    {
        $emails = Newsletter::orderBy('email', 'ASC')->paginate(20);

        return view('painel.newsletter.index', compact('emails'));
    }

    public function destroy(Newsletter $email)
    {
        try {

            $email->delete();
            return redirect()->route('painel.newsletter.index')->with('success', 'E-mail excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir e-mail: '.$e->getMessage()]);

        }
    }

    public function exportar()
    {
        $file = 'berzek-newsletter_'.date('d-m-Y_His');

        \Excel::create($file, function($excel) {
            $excel->sheet('emails', function($sheet) {
                $sheet->fromModel(Newsletter::orderBy('email', 'ASC')->get(['nome', 'email']));
            });
        })->download('csv');
    }
}

laravel/app/Http/Controllers/Painel/NovoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\NovoRequest;
use App\Http\Controllers\Controller;

use App\Models\Novo;
use App\Helpers\CropImage;

class NovoController extends Controller
{
    private $image_config = [
        'width'  => 290,
        'height' => null,
        'path'   => 'assets/img/novo/'
    ];

    public function index()
    {
        $novo = Novo::first();

        return view('painel.novo.index', compact('novo'));
    }

    public function update(NovoRequest $request, Novo $novo)
    {
        try {

            $input = array_filter($request->all(), 'strlen');

            if (isset($input['imagem'])) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            }

            if (isset($input['manual'])) {
                $input['manual'] = $this->uploadArquivo($input['manual']);
            }

            $novo->update($input);
            return redirect()->route('painel.novo.index')->with('success', 'Página alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar página: '.$e->getMessage()]);

        }
    }

    public function uploadArquivo($file)
    {
        $filePath = 'assets/downloads/';
        $fileName = preg_replace("([^\w\s\d\-_~,;:\[\]\(\).])", '', $file->getClientOriginalName());
        $fileName = date('YmdHis').'_'.$fileName;

        $file->move(public_path($filePath), $fileName);
        return $fileName;
    }
}

laravel/app/Http/Controllers/Painel/NovoImagensController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\NovoImagensRequest;
use App\Http\Controllers\Controller;

use App\Models\NovoImagem;
use App\Helpers\CropImage;

class NovoImagensController extends Controller
{
    private $image_config = [
        [
            'width'  => 180,
            'height' => 180,
            'path'   => 'assets/img/novo/imagens/thumbs/'
        ],
        [
            'width'  => 980,
            'height' => null,
            'upsize' => true,
            'path'   => 'assets/img/novo/imagens/'
        ]
    ];

    public function index()
    {
        $imagens = NovoImagem::ordenados()->get();

        return view('painel.novo.imagens.index', compact('imagens'));
    }

    public function store(NovoImagensRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $imagem = NovoImagem::create($input);
            $view   = view('painel.novo.imagens.imagem', compact('imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar imagem: '.$e->getMessage();

        }
    }

    public function destroy(NovoImagem $imagem)
    {
        try {

            $imagem->delete();
            return redirect()->route('painel.novo.imagens.index')
                             ->with('success', 'Imagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagem: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/produtos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Produtos /</small> Adicionar Produto</h2>
    </legend>

    {!! Form::open(['route' => 'painel.produtos.store', 'files' => true]) !!}

        @include('painel.produtos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@stop

laravel/resources/views/painel/produtos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Produtos /</small> Editar Produto</h2>
    </legend>

    {!! Form::model($produto, [
        'route'  => ['painel.produtos.update', $produto->id],
        'method' => 'patch',
        'files'  => true])
    !!}

        @include('painel.produtos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@stop

laravel/resources/views/painel/produtos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('produtos_categoria_id', 'Categoria') !!}
    {!! Form::select('produtos_categoria_id', $categorias, null, ['class' => 'form-control', 'placeholder' => 'Selecione']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem de Capa') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/produtos/'.$produto->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('descricao', 'Descrição') !!}
    {!! Form::textarea('descricao', null, ['class' => 'form-control ckeditor', 'data-editor' => 'produto']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.produtos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/produtos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Produtos
            <div class="btn-group pull-right">
                <a href="{{ route('painel.produtos.destaques.index') }}" class="btn btn-warning btn-sm"><span class="glyphicon glyphicon-star" style="margin-right:10px;"></span>Destaques</a>
                <a href="{{ route('painel.produtos.create') }}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Produto</a>
            </div>
        </h2>
    </legend>

    <div class="row" style="margin-bottom:20px">
        <div class="form-group col-sm-4">
            {!! Form::select('filtro', $categorias, Input::get('filtro'), ['class' => 'form-control', 'id' => 'filtro-select', 'placeholder' => 'Todas as Categorias', 'data-route' => 'painel/produtos']) !!}
        </div>
        <div class="col-sm-4" style="padding-left:0">
        <a href="{{ route('painel.produtos.categorias.index') }}" class="btn btn-primary btn-md"><span class="glyphicon glyphicon-edit" style="margin-right:10px;"></span><small>Editar Categorias</small></a>
        </div>
        @if(!$filtro)
        <div class="col-sm-4">
            <p class="alert alert-info small" style="margin-bottom: 15px; height:45px; padding: 12px 15px;">
                <span class="glyphicon glyphicon-info-sign" style="margin-right:10px;"></span>
                Selecione uma categoria para ordenar os produtos.
            </p>
        </div>
        @endif
    </div>

    @if(!count($produtos))
    <div class="alert alert-warning" role="alert">Nenhum produto cadastrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="produtos">
        <thead>
            <tr>
                @if($filtro)<th>Ordenar</th>@endif
                @if(!$filtro)<th>Categoria</th>@endif
                <th>Título</th>
                <th>Capa</th>
                <th>Imagens</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($produtos as $produto)
            <tr class="tr-row" id="{{ $produto->id }}">
                @if($filtro)
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                @endif
                @if(!$filtro)
                <td>
                    @if($produto->categoria){{ $produto->categoria->titulo }}@endif
                </td>
                @endif
                <td>
                    {{ $produto->titulo }}
                    @if($produto->destaque)
                    <span class="label label-warning" style="margin-left:3px;">destaque</span>
                    @endif
                </td>
                <td><img src="{{ url('assets/img/produtos/'.$produto->imagem) }}" alt="" style="width:100%;max-width:100px;height:auto;"></td>
                <td><a href="{{ route('painel.produtos.imagens.index', $produto->id) }}" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Gerenciar
                </a></td>
                <td class="crud-actions">
                    {!! Form::open(array('route' => array('painel.produtos.destroy', $produto->id), 'method' => 'delete')) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.produtos.edit', $produto->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection